# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
