# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20171008_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='tvshow',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
