# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_player_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='state',
            new_name='status',
        ),
    ]
