# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180101_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('standby', 'Awaiting players'), ('in_game', 'Game in progress')], default='standby', max_length=100),
        ),
    ]
