# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-07 15:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_player_player_session_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['-created']},
        ),
    ]
