# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-01 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180101_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('standby', 'Waiting in Lobby'), ('ready', 'Ready in Lobby'), ('in_game', 'Currently in Game')], default='standby', max_length=100),
        ),
    ]
